version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:g
      - echo Build started on `date`
      - sbt compile
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/scala-2.13/helloworld_scala_2.13-0.1.jar